
export const testMovie = {
    Actors: "Helen Hunt, Bill Paxton, Cary Elwes",
    Awards: "Nominated for 2 Oscars. 11 wins & 17 nominations total",
    BoxOffice: "$241,830,615",
    Country: "United States",
    DVD: "01 Apr 2010",
    Director: "Jan de Bont",
    Genre: "Action, Adventure, Thriller",
    Language: "English",
    Metascore: "68",
    Plot: "TV weatherman Bill Harding is trying to get his tornado-hunter wife, Jo, to sign divorce papers so he can marry his girlfriend Melissa. Bu…",
    Poster: "https://m.media-amazon.com/images/M/MV5BODExYTM0MzEtZGY2Yy00N2ExLTkwZjItNGYzYTRmMWZlOGEzXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    Production: "N/A",
    Rated: "PG-13",
    Ratings: [{"Source": "Internet Movie Database", "Value": "6.4/10"}, {"Source": "Rotten Tomatoes", "Value": "63%"}, {"Source": "Metacritic", "Value": "68/100"}],
    Released: "10 May 1996",
    Response: "True",
    Runtime: "113 min",
    Title: "Twister",
    Type: "movie",
    Website: "N/A",
    Writer: "Michael Crichton, Anne-Marie Martin",
    Year: "1996",
    imdbID: "tt0117998",
    imdbRating: "6.4",
    imdbVotes: "204,580",
};
